# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SimilarityPluginDialog
                                 A QGIS plugin
 Calculate score of similarity using GOF MapCurve (Vector & Raster)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-03-20
        git sha              : $Format:%H$
        copyright            : (C) 2020 by STIS
        email                : 16.9350@stis.ac.id
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.PyQt.QtWidgets import (
    QDialog, QVBoxLayout, QHBoxLayout, QFormLayout, QGroupBox,
    QLabel, QComboBox, QSpinBox, QDoubleSpinBox, QCheckBox,
    QPushButton, QTextEdit, QProgressBar, QTabWidget, QWidget,
    QLineEdit, QTextBrowser, QTableWidget, QHeaderView,
    QSizePolicy, QSpacerItem, QFrame
)
from qgis.PyQt.QtCore import QUrl
from qgis.PyQt.QtCore import Qt
from qgis.PyQt.QtGui import QFont

from qgis.gui import QgsMapLayerComboBox, QgsMapCanvas

import os


class SimilarityPluginDialog(QDialog):
    """Main dialog for Calculate Similarity Map plugin.

    Built with Qt layouts for responsive resizing.
    All widget attributes match the original .ui-loaded names
    so existing signal/slot code in similarity_plugin.py still works.
    """

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Calculate Similarity Map")
        self.setMinimumSize(880, 580)
        self.resize(1100, 680)
        self.setWindowFlags(self.windowFlags() | Qt.WindowMinMaxButtonsHint)
        self.setSizeGripEnabled(True)
        self._build_ui()
        self._init_compat_labels()

    # ------------------------------------------------------------------
    #  UI Builder
    # ------------------------------------------------------------------

    def _init_compat_labels(self):
        """Create compatibility label references for similarity_plugin.py.

        The old .ui-based dialog had explicit label widgets like labelOutOption_2,
        labelOutOption_9, etc. The new layout-based dialog uses QFormLayout which
        creates labels automatically. This method captures those labels so existing
        signal handlers in similarity_plugin.py still work.
        """
        for gb in self.findChildren(QGroupBox):
            if gb.title() == "Parameters":
                fmt = gb.layout()
                if isinstance(fmt, QFormLayout):
                    # Map field widgets to their labels
                    self.labelOutOption_2 = fmt.labelForField(self.lineEditTreshold)
                    self.labelOutOption_9 = fmt.labelForField(self.attrOutLineEdit)
                    self.labelOutOption_10 = fmt.labelForField(self.sufLineEdit)
                    self.labelOutOption_11 = fmt.labelForField(self.nnRadiusEdit)
                break

    def _build_ui(self):
        main_layout = QVBoxLayout(self)
        main_layout.setContentsMargins(6, 6, 6, 6)

        self.tabWidget = QTabWidget()
        self.tabWidget.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)

        # ---- Tab 1: Main ----
        self.mainTab = QWidget()
        self._build_main_tab()
        self.tabWidget.addTab(self.mainTab, "Main Tab")

        # ---- Tab 2: Help ----
        self.helpTab = QWidget()
        self._build_help_tab()
        self.tabWidget.addTab(self.helpTab, "Help")

        # ---- Tab 3: Console ----
        self.consoleTab = QWidget()
        self._build_console_tab()
        self.tabWidget.addTab(self.consoleTab, "Console Tab")

        main_layout.addWidget(self.tabWidget)
        self.setLayout(main_layout)

    # ==================================================================
    #  MAIN TAB
    # ==================================================================

    def _build_main_tab(self):
        layout = QHBoxLayout(self.mainTab)
        layout.setContentsMargins(8, 8, 8, 8)
        layout.setSpacing(10)

        # ---- Left Panel ----
        left = QWidget()
        left.setSizePolicy(QSizePolicy.Preferred, QSizePolicy.Expanding)
        left_layout = QVBoxLayout(left)
        left_layout.setSpacing(6)

        self._build_input_group(left_layout)
        self._build_method_group(left_layout)
        self._build_params_group(left_layout)
        left_layout.addStretch(1)
        self._build_action_group(left_layout)

        # ---- Right Panel ----
        right = QWidget()
        right.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        right_layout = QVBoxLayout(right)
        right_layout.setSpacing(6)

        self._build_preview_group(right_layout)

        # ---- Splitter ----
        splitter = QFrame()
        splitter.setFrameShape(QFrame.HLine)
        splitter.setFrameShadow(QFrame.Sunken)

        # Add left/right with proportions
        layout.addWidget(left, 2)   # 40%
        layout.addWidget(right, 3)  # 60%

    def _build_input_group(self, parent):
        """Input Layers group — layer selectors only (band auto-detected)."""
        gb = QGroupBox("Input Layers")
        fmt = QFormLayout(gb)
        fmt.setSpacing(4)
        fmt.setContentsMargins(8, 12, 8, 8)

        # Layer 1
        self.layerSel1 = QgsMapLayerComboBox()
        self.layerSel1.setAllowEmptyLayer(False)
        self.layerSel1.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        fmt.addRow("Layer 1:", self.layerSel1)

        # Layer 2
        self.layerSel2 = QgsMapLayerComboBox()
        self.layerSel2.setAllowEmptyLayer(False)
        self.layerSel2.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        fmt.addRow("Layer 2:", self.layerSel2)

        parent.addWidget(gb)

    def _build_method_group(self, parent):
        """Method selection group."""
        gb = QGroupBox("Method")
        vbox = QVBoxLayout(gb)
        vbox.setSpacing(4)
        vbox.setContentsMargins(8, 12, 8, 8)

        # Method combo
        row = QHBoxLayout()
        row.addWidget(QLabel("Algorithm:"), 0)
        self.methodComboBox = QComboBox()
        self.methodComboBox.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        self.methodComboBox.addItems([
            'Sequential',
            'Nearest Neighbour',
            'Wilkerstat BPS',
            'Raster'
        ])
        row.addWidget(self.methodComboBox, 1)
        vbox.addLayout(row)

        # Checkbox row
        check_row = QHBoxLayout()
        check_row.setSpacing(12)

        self.categoricalModeCheck = QCheckBox("Categorical Mode")
        self.categoricalModeCheck.setToolTip(
            "Exact class-label comparison (categorical data). "
            "Uncheck for continuous/tolerance-based comparison."
        )
        self.categoricalModeCheck.setEnabled(False)
        check_row.addWidget(self.categoricalModeCheck)

        self.mergeCenterCheck = QCheckBox("Merge Center")
        self.mergeCenterCheck.setEnabled(False)
        check_row.addWidget(self.mergeCenterCheck)

        check_row.addStretch(1)
        vbox.addLayout(check_row)

        parent.addWidget(gb)

    def _build_params_group(self, parent):
        """Parameters / output options group."""
        gb = QGroupBox("Parameters")
        fmt = QFormLayout(gb)
        fmt.setSpacing(4)
        fmt.setContentsMargins(8, 12, 8, 8)

        # Tolerance (repurposed as tolerance for raster, threshold for vector)
        self.lineEditTreshold = QDoubleSpinBox()
        self.lineEditTreshold.setDecimals(4)
        self.lineEditTreshold.setRange(0, 99999)
        self.lineEditTreshold.setValue(85.5555)
        self.lineEditTreshold.setToolTip("Threshold (%%) for vector | Tolerance for raster")
        self.percentLabel = QLabel("%")
        tol_row = QHBoxLayout()
        tol_row.addWidget(self.lineEditTreshold)
        tol_row.addWidget(self.percentLabel)
        fmt.addRow("Threshold:", tol_row)

        # KNN Radius (vector only)
        self.nnRadiusEdit = QDoubleSpinBox()
        self.nnRadiusEdit.setDecimals(4)
        self.nnRadiusEdit.setRange(0, 99999)
        self.nnRadiusEdit.setValue(0.05)
        self.nnRadiusEdit.setEnabled(False)
        fmt.addRow("KNN Radius:", self.nnRadiusEdit)

        # Resampling (raster only — NEW Phase 2)
        self.resamplingCombo = QComboBox()
        self.resamplingCombo.addItems(["Nearest", "Bilinear", "Cubic"])
        self.resamplingCombo.setCurrentIndex(0)  # Nearest
        self.resamplingCombo.setToolTip(
            "Resampling method when raster pixel sizes differ"
        )
        self.resamplingCombo.setEnabled(False)
        fmt.addRow("Resampling:", self.resamplingCombo)

        # Score attribute name (vector only)
        self.attrOutLineEdit = QLineEdit()
        self.attrOutLineEdit.setText("sim_score")
        fmt.addRow("Score attr:", self.attrOutLineEdit)

        # Suffix name (vector only)
        self.sufLineEdit = QLineEdit()
        self.sufLineEdit.setText("SIM_OUT")
        fmt.addRow("Suffix:", self.sufLineEdit)

        # Checkboxes row — kept for future use but hidden for now
        # (diff raster removed — output is via table)

        parent.addWidget(gb)

    def _build_action_group(self, parent):
        """Calculate / Stop / Save buttons + progress."""
        # Buttons row
        btn_row = QHBoxLayout()
        btn_row.setSpacing(6)

        self.calcBtn = QPushButton("Calculate")
        self.calcBtn.setMinimumWidth(80)
        btn_row.addWidget(self.calcBtn)

        self.stopBtn = QPushButton("Stop")
        self.stopBtn.setEnabled(False)
        self.stopBtn.setMinimumWidth(60)
        btn_row.addWidget(self.stopBtn)

        self.saveBtn = QPushButton("Save")
        self.saveBtn.setEnabled(False)
        self.saveBtn.setMinimumWidth(60)
        btn_row.addWidget(self.saveBtn)

        btn_row.addStretch(1)

        self.eventLabel = QLabel("")
        self.eventLabel.setStyleSheet("color: #555; font-size: 10px;")
        btn_row.addWidget(self.eventLabel)

        parent.addLayout(btn_row)

        # Progress row
        prog_row = QHBoxLayout()
        prog_row.setSpacing(6)

        self.progressBar = QProgressBar()
        self.progressBar.setValue(0)
        self.progressBar.setTextVisible(True)
        prog_row.addWidget(self.progressBar, 1)

        self.counterLabel = QLabel("Number of Result: 0")
        self.counterLabel.setStyleSheet("font-size: 10px;")
        prog_row.addWidget(self.counterLabel)

        parent.addLayout(prog_row)

    # ==================================================================
    #  PREVIEW PANEL (Right side)
    # ==================================================================

    def _build_preview_group(self, parent):
        """Score display, results table, map canvas, nav buttons."""

        # Score header
        score_row = QHBoxLayout()
        score_label = QLabel("Score:")
        score_label.setFont(QFont("", 10, QFont.Bold))
        self.labelScore = QLabel("0")
        self.labelScore.setFont(QFont("", 10, QFont.Bold))
        score_row.addWidget(score_label)
        score_row.addWidget(self.labelScore, 1)
        parent.addLayout(score_row)

        # Results table (per-band GOF scores)
        self.resultsTable = QTableWidget(0, 5)
        self.resultsTable.setHorizontalHeaderLabels(
            ["Band", "Raster 1", "Raster 2", "Match", "GOF"]
        )
        self.resultsTable.horizontalHeader().setStretchLastSection(True)
        self.resultsTable.setMaximumHeight(130)
        self.resultsTable.setAlternatingRowColors(True)
        self.resultsTable.setVisible(False)  # hidden until results ready
        parent.addWidget(self.resultsTable)

        # Save CSV button (hidden until results)
        csv_row = QHBoxLayout()
        csv_row.addStretch(1)
        self.saveCsvBtn = QPushButton("💾 Save CSV")
        self.saveCsvBtn.setEnabled(False)
        self.saveCsvBtn.setVisible(False)
        csv_row.addWidget(self.saveCsvBtn)
        parent.addLayout(csv_row)

        # Attribute text edits (kept for vector preview compatibility)
        attr_row = QHBoxLayout()
        attr_row.setSpacing(6)
        self.previewAttr = QTextEdit()
        self.previewAttr.setReadOnly(True)
        self.previewAttr.setMaximumHeight(60)
        self.previewAttr.setVisible(False)
        attr_row.addWidget(self.previewAttr)
        self.previewAttr_2 = QTextEdit()
        self.previewAttr_2.setReadOnly(True)
        self.previewAttr_2.setMaximumHeight(60)
        self.previewAttr_2.setVisible(False)
        attr_row.addWidget(self.previewAttr_2)
        parent.addLayout(attr_row)

        # Map canvas
        self.widgetCanvas = QgsMapCanvas()
        self.widgetCanvas.setMinimumHeight(180)
        self.widgetCanvas.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        parent.addWidget(self.widgetCanvas, 1)

        # Navigation buttons
        nav_row = QHBoxLayout()
        nav_row.setSpacing(6)

        self.previousBtn = QPushButton("◀ Prev")
        self.previousBtn.setEnabled(False)
        nav_row.addWidget(self.previousBtn)

        self.nextBtn = QPushButton("Next ▶")
        self.nextBtn.setEnabled(False)
        nav_row.addWidget(self.nextBtn)

        self.removeBtn = QPushButton("✕ Remove")
        self.removeBtn.setEnabled(False)
        nav_row.addWidget(self.removeBtn)

        nav_row.addStretch(1)
        parent.addLayout(nav_row)

    # ==================================================================
    #  HELP TAB
    # ==================================================================

    def _build_help_tab(self):
        layout = QVBoxLayout(self.helpTab)
        layout.setContentsMargins(8, 8, 8, 8)

        # Use QTextBrowser instead of QWebView for compatibility
        self.helpTextBrowser = QTextBrowser()
        self.helpTextBrowser.setOpenExternalLinks(True)
        layout.addWidget(self.helpTextBrowser, 1)

        # Nav buttons
        btn_row = QHBoxLayout()
        btn_row.addStretch(1)

        self.previousHelpBtn = QPushButton("◀ Previous")
        btn_row.addWidget(self.previousHelpBtn)

        self.nextHelpBtn = QPushButton("Next ▶")
        btn_row.addWidget(self.nextHelpBtn)

        layout.addLayout(btn_row)

    # ==================================================================
    #  CONSOLE TAB
    # ==================================================================

    def _build_console_tab(self):
        layout = QVBoxLayout(self.consoleTab)
        layout.setContentsMargins(8, 8, 8, 8)

        self.consoleTextEdit = QTextEdit()
        self.consoleTextEdit.setReadOnly(True)
        self.consoleTextEdit.setStyleSheet(
            "font-family: 'Consolas', 'Courier New', monospace;"
        )
        layout.addWidget(self.consoleTextEdit, 1)

    # ------------------------------------------------------------------
    #  Helpers
    # ------------------------------------------------------------------

    def append_console(self, text: str):
        """Append text to the console tab."""
        self.consoleTextEdit.append(text)

    def clear_console(self):
        """Clear the console tab."""
        self.consoleTextEdit.clear()
